config/routes.rb
Quora::Application.routes.draw do
  root :to => "home#index"

  match "/uploads/*path" => "gridfs#serve"
  match "/update_in_place" => "home#update_in_place"
  match "/muted" => "home#muted"
  match "/newbie" => "home#newbie"
  match "/followed" => "home#followed"
  match "/recommended" => "home#recommended"
  match "/mark_notifies_as_read" => "home#mark_notifies_as_read"
  match "/mute_suggest_item" => "home#mute_suggest_item"
  match "/report" => "home#report"
  match "/about" => "home#about"
  match "/doing" => "logs#index"

  # devise_for :users, :path => '', :path_names => {:sign_in => "login", :sign_out => "logout", :sign_up => "register", :registration }
  devise_for :users,  :controllers => { :registrations => "registrations" } do
    # get "/register", :to => "registrations#new" 
    # get "/login", :to => "devise/sessions#new" 
    # get "/logout", :to => "devise/sessions#destroy" 
  end
  resources :users do
    member do
      get "answered"
      get "asked"
      get "asked_to"
      get "follow"
      get "unfollow"
      get "followers"
      get "following"
      get "following_topics"
      get "following_asks"
    end
  end
  match "login", :to => "users#login"
  match "logout", :to => "users#logout"
  match "auth/:provider/callback", :to => "users#auth_callback"  

  resources :search do
    collection do
      get "all"
      get "topics"
      get "asks"
      get "users"
    end
  end
  
  resources :asks do
    member do
      get "spam"
      get "follow"
      get "unfollow"
      get "mute"
      get "unmute"
      post "answer"
      post "update_topic"
      get "update_topic"
      get "redirect"
      get "invite_to_answer"
      get "share"
      post "share"
    end
  end

  resources :answers do
    member do
      get "vote"
      get "spam"
      get "thank"
    end
  end
  resources :comments 

  resources :topics, :constraints => { :id => /[a-zA-Z\w\s\.%\-_]+/ } do
    member do
      get "follow"
      get "unfollow"
    end
  end
  resources :logs
  resources :inbox

  namespace :cpanel do
    root :to =>  "home#index"
    resources :users
    resources :asks
    resources :answers
    resources :topics
    resources :comments
    resources :report_spams
    resources :notices
  end

  mount Resque::Server, :at => "/cpanel/resque"
end

app/controllers/asks_controller.rb
# coding: UTF-8
class AsksController < ApplicationController
  before_filter :require_user, :only => [:answer]
  before_filter :require_user_js, :only => [:answer,:invite_to_answer]
  before_filter :require_user_text, :only => [:update_topic,:redirect,:spam, :mute, :unmute, :follow, :unfollow]
  
  def index
    @per_page = 20
    @asks = Ask.normal.recent.includes(:user).paginate(:page => params[:page], :per_page => @per_page)
    set_seo_meta("所有问题")
  end

  def search
    # @asks = Ask.search_title(params["w"],:limit => 20)[:items]
    set_seo_meta("关于“#{params[:w]}”的搜索结果")
    render "index"
  end

  def show
    @ask = Ask.find(params[:id])
    @ask.view!

    if !@ask.redirect_ask_id.blank?
      if params[:nr].blank?
        # 转向问题
        redirect_to ask_path(@ask.redirect_ask_id,:rf => params[:id], :nr => "1")
        return
      else
        @r_ask = Ask.find(@ask.redirect_ask_id)
      end
    end

    if params[:rf]
      @rf_ask = Ask.find(params[:rf])
      if !@ask.redirect_ask_id.blank?
        @r_ask = Ask.find(@ask.redirect_ask_id)
      end
    end
    
    # 由于 voteable_mongoid 目前的按 votes_point 排序有问题，没投过票的无法排序
    @answers = @ask.answers.includes(:user).order_by(:"votes.uc".desc,:"votes.dc".asc,:"created_at".asc)
    @answer = Answer.new
    # 推荐话题,如果没有设置话题的话
    @suggest_topics = AskSuggestTopic.find_by_ask(@ask)
    set_seo_meta(@ask.title)

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  def redirect
    return render :text => "-2" if params[:id] == params[:new_id]
    @ask = Ask.find(params[:id])
    if params[:cancel].blank?
      render :text => @ask.redirect_to_ask(params[:new_id])
    else
      @ask.redirect_cancel
      render :text => "1"
    end
  end

  def share
    @ask = Ask.find(params[:id])
    if request.get?
      if current_user
        render "share", :layout => false
      else
        render_404
      end
    else
      case params[:type]
      when "email"
        UserMailer.simple(params[:to], params[:subject], params[:body].gsub("\n","<br />")).deliver
        @success = true
        @msg = "已经将问题连接发送到了 #{params[:to]}"
      end
    end

  end

  def answer
    @answer = Answer.new(params[:answer])
    @answer.ask_id = params[:id]
    @answer.user_id = current_user.id
    
    @answer.body = simple_format(@answer.body.strip) if params[:did_editor_content_formatted] == "no"
    
    if @answer.save
      @success = true
    else
      @success = false
    end

  end

  def spam 
    @ask = Ask.find(params[:id])
    size = 1
    if(Setting.admin_emails.include?(current_user.email))
      size = Setting.ask_spam_max
    end
    count = @ask.spam(current_user.id,size)
    render :text => count
  end

  def follow
    @ask = Ask.find(params[:id])
    if params[:follow].blank?
      follow = false
    else
      follow = true
    end
    res = current_user.follow_ask(@ask,follow)
    render :text => res
  end
  
  def new
    @ask = Ask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end
  
  def edit
    @ask = Ask.find(params[:id])
  end
  
  def create
    @ask = Ask.find_by_title(params[:ask][:title])
    if @ask
      flash[:notice] = "已有相同的问题存在，已重定向。"
      redirect_to ask_path(@ask.id)
      return 
    end
    @ask = Ask.new(params[:ask])
    @ask.user_id = current_user.id
    @ask.followers << current_user
    @ask.current_user_id = current_user.id

    respond_to do |format|
      if @ask.save
        format.html { redirect_to(ask_path(@ask.id), :notice => '问题创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end
  
  def update
    @ask = Ask.find(params[:id])
    @ask.current_user_id = current_user.id

    respond_to do |format|
      if @ask.update_attributes(params[:ask])
        format.html { redirect_to(ask_path(@ask.id), :notice => '问题更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end

  def update_topic
    @name = params[:name].strip
    @add = params[:add] == "1" ? true : false

    @ask = Ask.find(params[:id])
    if @ask.update_topics(@name,@add,current_user.id)
      @success = true
    else
      @success = false
    end
    if not @add
      render :text => @success
    end
  end

  def mute
    @ask = Ask.find(params[:id])
    if not @ask
      render :text => "0"
      return
    end
    current_user.mute_ask(@ask.id)
    render :text => "1"
  end
  
  def unmute
    @ask = Ask.find(params[:id])
    if not @ask
      render :text => "0"
      return
    end
    current_user.unmute_ask(@ask.id)
    render :text => "1"
  end
  
  def follow
    @ask = Ask.find(params[:id])
    if not @ask
      render :text => "0"
      return
    end
    current_user.follow_ask(@ask)
    render :text => "1"
  end
  
  def unfollow
    @ask = Ask.find(params[:id])
    if not @ask
      render :text => "0"
      return
    end
    current_user.unfollow_ask(@ask)
    render :text => "1"
  end

  def invite_to_answer
    drop = params[:drop] == "1" ? true : false
    if drop
      result = AskInvite.cancel(params[:i_id], current_user.id)
      render :text => "1"
    else
      if (current_user.id.to_s != params[:user_id].to_s)
        @invite = AskInvite.invite(params[:id], params[:user_id], current_user.id)
        @success = true
      else
        @success = false
      end
    end
  end
  
end

app/controllers/cpanel/asks_controller.rb
# coding: UTF-8
class Cpanel::AsksController < CpanelController
  
  def index
    @asks = Ask.includes([:user]).desc("created_at").paginate(:page => params[:page], :per_page => 40)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @ask = Ask.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end
  
  def new
    @ask = Ask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end
  
  def edit
    @ask = Ask.find(params[:id])
  end
  
  def create
    @ask = Ask.new(params[:ask])

    respond_to do |format|
      if @ask.save
        format.html { redirect_to(cpanel_asks_path, :notice => 'Ask 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end
  
  def update
    @ask = Ask.find(params[:id])

    respond_to do |format|
      if @ask.update_attributes(params[:ask])
        format.html { redirect_to(cpanel_asks_path, :notice => 'Ask 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end
  
  def destroy
    @ask = Ask.find(params[:id])
    @ask.destroy

    respond_to do |format|
      format.html { redirect_to(cpanel_asks_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/helpers/asks_helper.rb
# coding: utf-8
module AsksHelper
  def topics_name_tag(topics,limit = 20)
    html = []
    return "" if topics.blank?
    if limit > 0
      topics = topics[0,limit]
    end
    for topic in topics
      html << "<a class=\"topic\" href=\"/topics/#{topic}\">#{h(topic)}</a>"
    end
    return raw html.join("")
  end

  def ask_title_tag(ask, options = {})
    class_name = options[:class] || ""
    prefix = ""
    if !ask.to_user.blank?
      prefix = "#{ask.to_user.name}："
    end
    raw "<a href=\"/asks/#{ask.id}\" class=\"#{class_name}\">#{h(prefix)}#{h(ask.title)}</a>"
  end

  def md_body(str)
    return "" if str.blank?
    # str = simple_format(str) if str =~ /\n/
    # Rails.logger.info "str: #{str.inspect}"
    str = sanitize(str,:tags => %w(strong b i u strike s ol ul li blockquote address br p), :attributes => %w(src))
    str = auto_link_urls(str,{:target => "_blank", :rel => "nofollow" }, {:limit => 80 })
    return raw str
  end

  def truncate_lines(body, lines = 4, max_chars = 400)
    return "" if body.blank?
    body_lines = body.split("\n")
    lines = body_lines.count if body_lines.count < lines
    summary = body_lines[0,lines].join("\n")
    summary = inner_truncate_lines(body_lines, lines - 1, summary, max_chars)
    return summary
  end

  # 检测是否 Vote 过 Answer
  def voted?(answer,type = :up)
    return false if current_user.blank?
    if type == :up
      return false if answer.up_voter_ids.blank?
      return answer.up_voter_ids.count(current_user.id) > 0
    else
      return false if answer.down_voter_ids.blank?
      return answer.down_voter_ids.count(current_user.id) > 0
    end
  end

  # 检测是否 Spam 过 Ask 
  def spamed?(ask)
    return false if current_user.blank? or ask.spam_voter_ids.blank?
    return ask.spam_voter_ids.count(current_user.id) > 0
  end

  # 判断是否是 spam 的问题
  def spam_ask?(ask)
    point = ask.spams_count || 0
    return point >= Setting.ask_spam_max
  end

  # 判断是否是 spam 的回答
  def spam_answer?(answer)
    point = answer.spams_count || 0
    return point >= Setting.answer_spam_max
  end

  # 判断是否是 spam 过这个回答
  def spam_answered?(answer)
    return false if current_user.blank?
    return false if answer.spam_voter_ids.blank?
    return answer.spam_voter_ids.count(current_user.id) > 0
    return
  end

  def thank_answered?(answer)
    return false if current_user.blank?
    return false if current_user.thanked_answer_ids.blank?
    return current_user.thanked_answer_ids.count(answer.id) > 0
    return
  end

  private
  def inner_truncate_lines(body_lines, lines, summary, max_chars)
    if summary.length > max_chars
      lines -= 1
      if lines > 1
        body_lines = body_lines[0,lines]
        summary = body_lines.join("\n")
        return inner_truncate_lines(body_lines, lines, summary, max_chars)
      else
        summary = body_lines[0][0,max_chars]
        return summary
      end
    else
      return summary
    end
  end

  
end

app/helpers/cpanel/asks_helper.rb
module Cpanel::AsksHelper
end

app/views/asks/1__sidebar.html.erb.bak.erb
<% content_for :sidebar do %>
  <div class="box">
    <ul class="sections">
      <% if current_user %>
			<li>
    		<a href="<%= root_path %>" class="home<%= ' active' if params[:controller] == "home" and ["index","newbie"].index(params[:action]) %>">我的首页</a>
    	</li>
			<li>
    		<a href="<%= followed_path %>" class="followed<%= ' active' if params[:controller] == "home" and params[:action] == "followed" %>">我关注的问题</a>
    	</li>
			<li>
    		<a href="<%= recommended_path %>" class="recommended<%= ' active' if params[:controller] == "home" and params[:action] == "recommended" %>">推荐给我的问题</a>
    	</li>
    	<li>
    		<a href="<%= muted_path %>" class="muted<%= ' active' if params[:controller] == "home" and params[:action] == "muted" %>">我屏蔽的问题</a>
    	</li>
			<li>
        <a href="<%= asks_path %>" class="asks<%= ' active' if params[:controller] == "asks" and params[:action] == "index" %>">所有问题</a>
      </li>
      <% else %>
        <li> <a href="<%= root_path %>" class="asks<%= ' active' if params[:controller] == "home" and params[:action] == "index" %>">所有问题</a> </li>
			<% end %>
			<li>
        <a href="<%= doing_path %>" class="logs<%= ' active' if params[:controller] == "logs" and params[:action] == "index" %>">者也正在发生</a>
      </li>
    </ul>
  </div>
	<% if current_user %>
		<div class="box">
			<h2>邀请好友</h2>
	    <ul class="sections">
				<li>
		      <a href="<%= new_user_invitation_path %>">邀请你的朋友注册</a>
		    </li>
			</ul>
		</div>
	
    <% 
      items = current_user.suggest_items
      if !items.blank?
    %>
      <div class="box">
        <h2>你可能会感兴趣的人或话题</h2>
        <ul class="followed-item listing">
          <% for item in items %>
            <% if item.class.to_s == 'User' %>
            <%= render "home/recommended_user", :follower => item %>
            <% elsif item.class.to_s == 'Topic' %>
            <%= render "home/recommended_topic", :topic => item %>
            <% end %>
          <% end %>
        </ul>
      </div>
      <script type="text/javascript">
        $("ul.followed-item li").mouseenter(function(){ $(this).find(".mute").show(); }).mouseleave(function(){ $(this).find(".mute").hide(); });
      </script>
    <% end %>
  <% end %>
<% end %>

app/views/asks/1_edit.html.erb.bak.erb
<%= content_for :sitemap do %>
<span class="current">修改</span>
<% end %>
<%= render 'base' %>
<%= render 'form' %>

app/views/asks/1_invite_to_answer.js.erb.bak.erb
<% if @success %>
i = $("#ask_invite_<%= @invite.id %>");
if(i.length == 0){
  $("#ask_invited_users").append('<%= escape_javascript(render("invited_user", :item => @invite)) %>');
}
else{
  $(".count",i).text('<%= @invite.count %>');
}
<% end %>
App.loading(false);

app/views/asks/1_share.js.erb.bak.erb
<% if @success %>
  App.notice('<%= @msg %>');
  $.facebox.close();
<% else %>
  alert('<%= @msg %>');
<% end %>

app/views/asks/1_show.mobile.erb.bak.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    var ask_id = '<%= @ask.id %>';
    var ask_redirected = false;
  </script>
<% end %>
<%= render 'base' %>
<% if not @rf_ask.blank? %>
  <script type="text/javascript">
    Asks.redirected_tip('<%= @rf_ask.title %>', '<%= @rf_ask.id %>','rf');
  </script>
<% end %>
<% if not @r_ask.blank? %>
  <script type="text/javascript">
    ask_redirected = true;
    Asks.redirected_tip('<%= @r_ask.title %>', '<%= @r_ask.id %>','nr', '<%= @ask.id %>');
  </script>
<% end %>
<div class="ask the-ask" id="ask_<%= @ask.id %>">
  <% if current_user %>
  <div class="follow_buttons">
    <div class="box">
      <div class="inner">
        <% if current_user.ask_followed?(@ask) %>
        <a href="#" style="width:80px;" class="flat_button" onclick="return Asks.unfollow(this);">取消关注</a>
        <% else %>
        <a href="#" style="width:80px;" class="gray_button green_button" onclick="return Asks.follow(this);">关注此问题</a>
        <% end %>
        <a href="#" class="dropdown" onclick="return Asks.dropdown_menu(this);"><span class="settings">选项</span></a>
      </div>
    </div>
  </div>
  <% end %>
  <div class="topics">
    <div class="item_list">
      <% if !@ask.topics.blank? %>
        <%= topics_name_tag(@ask.topics) %>
      <% else %>
        <% if current_user %>
          <span class="no_result">给这个问题选个话题吧，好让别人来回答</span>
        <% end %>
      <% end %>
      <% if can_edit?(@ask) %>
        <a href="#" onclick="return Asks.toggleEditTopics(true);" class="in_place_edit">修改</a>
      <% end %>
    </div>
    <div class="edit_topics" style="display:none">
      <div class="items">
        <% if !@ask.topics.blank? %>
          <% @ask.topics.each_with_index do |item,i| %>
          <div class="topic">
            <a href="#" onclick="Asks.removeTopic(this,<%= i %>,'<%= item %>');" class="remove"></a>
            <span><%= item %></span>
          </div>
          <% end %>
        <% end %>
      </div>
      <form data-remote="true" action="<%= ask_path(@ask.id) %>/update_topic" onsubmit="return Asks.beforeAddTopic(this);" method="post">
        <%= auth_token  %>
        <input type="text" class="name" id="searchTopic" style="width:100px;" name="name" value="" placeholder="搜索话题" /> 
        <input type="hidden" name="add" value="1" /> 
        <button type="submit" class="small">添加</button> 
        <a href="#" onclick="return Asks.toggleEditTopics(false);">完成</a>
      </form>
      <script type="text/javascript">Asks.completeTopic($("#searchTopic"));</script>
    </div>
  </div>
  <div class="title">
    <h1><%= "#{@ask.to_user.name}：" if !@ask.to_user.blank? %><span id="ask_title"><%= @ask.title %></span></h1>
    <% if can_edit?(@ask) %>
      <%= in_place_edit_tag @ask, :title, :type => :textarea, :width => 300, :height => 40, :rich => false, :text_id => "ask_title" %>
    <% end %>
  </div>
  <div class="md_body">
    <div id="ask_body"<% if @ask.chomp_body.blank? %> class="blank-body"<% end %>><%= md_body(@ask.chomp_body) %></div>
    <% if can_edit?(@ask) %>
      <% if @ask.chomp_body.blank? %>
        <%= in_place_edit_tag @ask, :body, :type => :textarea, :text_id => "ask_body",:label => "添加补充资料" %>
      <% else %>
        <%= in_place_edit_tag @ask, :body, :type => :textarea, :text_id => "ask_body" %>
      <% end %>
    <% end %>
  </div>
  <div class="action">
    <% if @ask.comments_count == 0 %>
      <a href="#" onclick="return Asks.toggleComments('ask','<%= @ask.id %>');">添加评论</a>
    <% else %>
      <a href="#" onclick="return Asks.toggleComments('ask','<%= @ask.id %>');"><%= @ask.comments_count %> 条评论</a>
    <% end %>
    • <a href="#new_answer" onclick="return $('#new_answer .qeditor_preview').focus();">添加答案</a>
    • <a href="#" onclick="return Asks.report(this);">举报</a>
    • <a class="spam<%= ' spamed' if spamed?(@ask) %>" onclick="return Asks.spamAsk(this,'<%= @ask.id %>');" title="问题被<%= Setting.ask_spam_max %>个网友认为是烂问题以后,问题将会隐藏。" href="#">烂问题</a>
    <% if !@ask.spams_count.blank? %>(<span id="spams_count"><%= @ask.spams_count %></span>人认为)<% end %>
    • <span class="date"><%= l @ask.created_at.getlocal, :format => :short %></span>
  </div>
</div>

<% if @ask.answers_count > 0 %>
<div class="answers-count">
	有<%= @ask.answers_count %>个回答
</div>
<% end %>

<div class="answers">
  <% user_answered = false %>
  <% if !@answers.blank? %>
    <% @answers.each do |item| %>
      <% user_answered = true if owner?(item) %>
      <%= render("answer", :item => item) %>
    <% end %>
  <% end %>
</div>

<% if current_user %>
  <% if user_answered %>
    <div class="disabled_answer">一个问题你只能回答一次，但你可以对现有的回答进行修改。</div>
  <% elsif !@ask.to_user.blank? and current_user.id != @ask.to_user_id %>
    <div class="disabled_answer">这个问题是对 <%= user_name_tag(@ask.to_user) %> 提问的，只有<%= user_sex_title(@ask.to_user) %>才能回答。</div>
  <% else %>
    <div class="answer_form from">
      <h2>添加答案</h2>
      <% if current_user %>
      <div class="user_info">
        <%= user_name_tag(current_user) %>,
        <span id="answer_user_tagline"><%= user_tagline_tag(current_user) %></span>
        <%= in_place_edit_tag current_user, :tagline, :text_id => "answer_user_tagline", :label => "修改简介" %>
      </div>
      <% end %>
      <%= form_for(@answer, :remote => true, :html => { :onsubmit => "return Asks.beforeAnswer(this);" },
                   :url => answer_ask_path(@ask.id)) do |f| %>
        <div class="row">
          <%= f.text_area :body, :style => "height:100px;", :class => "text long" %>
        </div>
        <div class="actions">
          <button class="submit" type="submit">提交回答</button>
        </div>
      <% end %>
      <script type="text/javascript">
        $("#answer_body").qeditor({'is_mobile_device': <%= is_mobile_device? ? 'true' : 'false' %>});
      </script>
    </div>
  <% end %>
<% end %>
<% content_for :sidebar do %>
<% end %>
<div id="ask_sidebar" class="sidebar">
  <div style="display:none" id="redirect_ask">
    <div id="redirect_ask_panel" class="facebox_window simple_form">
      <h2>指向另外个已经存在的问题</h2>
      <form action="" onsubmit="return Asks.redirect_ask_save(this);">
        <div class="field">
          <label>把问题“<%= @ask.title %>”指向:</label>
          <input type="text" class="search" style="width:250px;" placeholder="搜索标题" />
          <input type="hidden" class="r_title" />
          <input type="hidden" class="r_id" />
        </div>
        <div class="actions">
          <button type="submit">确定重定向</button>
          <a style="margin-left:10px;" onclick="$.facebox.close(); return false;" href="#">取消</a>
        </div>
      </form>
    </div>
  </div>


  <div id="relation_asks" class="box standard">
    <h2>相关问题</h2>
    <div class="inner">
      <ul>
      <% @relation_asks.each_with_index do |ask,i| %>
        <li <%= "style='display:none;'" if i > 4 %>><a href="/asks/<%= ask.id %>"><%= ask.title %></a></li>
      <% end %>
      <% if @relation_asks.count > 4 %>
        <li class="more">
          <a href="#" onclick="$(this).parent().parent().find('li').show();$(this).hide();return false;">查看更多相关问题</a>
        </li>
      <% end %>
      <ul>
    </div>
  </div>

  <div class="box standard gray">
    <h2>问题状态</h2>
    <div class="inner">
      <p>最近活动：<%= l @ask.last_updated_at ? @ask.last_updated_at.getlocal : (@ask.answered_at ? @ask.answered_at.getlocal : @ask.updated_at.getlocal), :format => :min %></p>
      <p>被浏览 <%= @ask.views_count %> 次，<%= @ask.followers.count %> 人关注了该问题</p>
      <% if @ask.user %>
      <p><%= user_name_tag(@ask.user) %> 创建了该问题</p>
      <% end %>
      <div class="followers">
        <% for item in @ask.followers %>
          <%= user_avatar_tag(item,:small) %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if params[:eawc] == "yes" or params[:easc] == "yes" %>
	<% content_for :scripts do %>
	  <script type="text/javascript">
			$(document).ready(function() {
				Asks.toggleComments('<%= params[:eawc] == "yes" ? "answer" : "ask" %>','<%= params[:eawc] == "yes" ? params[:awid] : params[:asid] %>');
			});
		</script>
	<% end %>
<% end %>

app/views/asks/_form.erb
<div id="ask">
<%= simple_form_for(@ask) do |f| %>
  <div class="inputs">
    <%= f.input :title, :label => "#{t(:title)}", :input_html => {:class => "long"}%>
    <%= f.input :body, :label => "#{t(:text)}", :as => :text, :input_html => {:class => "long"} %>
      <script type="text/javascript">
        $("#ask_body").qeditor({'is_mobile_device': <%= is_mobile_device? ? 'true' : 'false' %>});
      </script>
  </div>
  <div class="actions">
    <button class="submit"><%=t(:submit_a_question)%></button> 或者 <%= link_to "#{t(:back)}", asks_path %>
  </div>
<% end %>
</div>

app/views/asks/_recommended_ask.html.erb
<div class="ask" ask-id="<%= item.id %>">
  <div class="title"><a href="/asks/<%= item.id %>"><%= item.title %></a></div>
    <div class="info">
      <%=t(:the_problem_is_added_to_the)%> <%= raw item.topics.map {|t| "<a href=\"/topics/#{t}\">#{t}</a>"}.join("、") %> <%=t(:this)%><%= item.topics.size %><%=t(:topics)%>
    </div> 
</div>

app/views/asks/_sidebar.mobile.erb
<% content_for :sidebar do %>
  <ul id="main_sections" class="clearfix">
    <% if current_user %>
    <li>
      <a href="<%= root_path %>" class="home<%= ' active' if params[:controller] == "home" and ["index","newbie"].index(params[:action]) %>">首页</a>
    </li>
    <li>
      <a href="<%= asks_path %>" class="asks<%= ' active' if params[:controller] == "asks" and params[:action] == "index" %>"><%=t(:all_issues)%></a>
    </li>
    <% else %>
      <li> <a href="<%= root_path %>" class="asks<%= ' active' if params[:controller] == "home" and params[:action] == "index" %>">首页</a> </li>
    <% end %>
    <li>
      <a href="<%= doing_path %>" class="logs<%= ' active' if params[:controller] == "logs" and params[:action] == "index" %>"><%=t(:news)%></a>
    </li>
  </ul>
<% end %>

app/views/asks/answer.js.erb
<% if @success %>
html = "<%= escape_javascript(render("answer", :item => @answer)) %>";
$("#answer_body").text("").focus();
answer = $(html);
$(".answers").append(answer);
answerPreview = $("#answer_body").next();
answerPreview.html("");
answerPreview.focus();
answer.fadeOut(100).fadeIn(200);
$(".answer_form").remove();
<% else %>
$("#answer_body").focus();
<% end %>
App.loading(false);
$(".answer_form button.submit").attr("disabled",false);

app/views/asks/edit.html.erb
<%= content_for :sitemap do %>
<span class="current"><%=t(:modify)%></span>
<% end %>
<%= render 'base' %>
<%= render 'form' %>

app/views/asks/index.js.erb
<% if !@asks.blank? %>
  <% @asks.each do |item| %>
    $(".pagination").before('<%= escape_javascript(render("/asks/ask",:item => item)) %>');
  <% end %>
  current_page = "<%= (params[:page] || "1").to_i + 1 %>";
  <% if @asks.count < @per_page %>
  $(".pagination").remove();
  <% end %>
<% else %>
  $(".pagination").remove();
<% end %>

app/views/asks/new.erb
<%= content_for :sitemap do %>
<span class="current">新建</span>
<% end %>
<%= render 'base' %>
<%= render 'form' %>

app/views/asks/recommended.js.erb
<% if !@asks.blank? %>
  <% @asks.each do |item| %>
    $(".pagination").before('<%= escape_javascript(render("/asks/recommended_ask",:item => item)) %>');
  <% end %>
  current_page = "<%= (params[:page] || "1").to_i + 1 %>";
  <% if @asks.count < @per_page %>
  $(".pagination").remove();
  <% end %>
<% else %>
  $(".pagination").remove();
<% end %>