config/routes.rb
Quora::Application.routes.draw do
  root :to => "home#index"

  match "/uploads/*path" => "gridfs#serve"
  match "/update_in_place" => "home#update_in_place"
  match "/muted" => "home#muted"
  match "/newbie" => "home#newbie"
  match "/followed" => "home#followed"
  match "/recommended" => "home#recommended"
  match "/mark_notifies_as_read" => "home#mark_notifies_as_read"
  match "/mute_suggest_item" => "home#mute_suggest_item"
  match "/report" => "home#report"
  match "/about" => "home#about"
  match "/doing" => "logs#index"

  # devise_for :users, :path => '', :path_names => {:sign_in => "login", :sign_out => "logout", :sign_up => "register", :registration }
  devise_for :users,  :controllers => { :registrations => "registrations" } do
    # get "/register", :to => "registrations#new" 
    # get "/login", :to => "devise/sessions#new" 
    # get "/logout", :to => "devise/sessions#destroy" 
  end
  resources :users do
    member do
      get "answered"
      get "asked"
      get "asked_to"
      get "follow"
      get "unfollow"
      get "followers"
      get "following"
      get "following_topics"
      get "following_asks"
    end
  end
  match "login", :to => "users#login"
  match "logout", :to => "users#logout"
  match "auth/:provider/callback", :to => "users#auth_callback"  

  resources :search do
    collection do
      get "all"
      get "topics"
      get "asks"
      get "users"
    end
  end
  
  resources :asks do
    member do
      get "spam"
      get "follow"
      get "unfollow"
      get "mute"
      get "unmute"
      post "answer"
      post "update_topic"
      get "update_topic"
      get "redirect"
      get "invite_to_answer"
      get "share"
      post "share"
    end
  end

  resources :answers do
    member do
      get "vote"
      get "spam"
      get "thank"
    end
  end
  resources :comments 

  resources :topics, :constraints => { :id => /[a-zA-Z\w\s\.%\-_]+/ } do
    member do
      get "follow"
      get "unfollow"
    end
  end
  resources :logs
  resources :inbox

  namespace :cpanel do
    root :to =>  "home#index"
    resources :users
    resources :asks
    resources :answers
    resources :topics
    resources :comments
    resources :report_spams
    resources :notices
  end

  mount Resque::Server, :at => "/cpanel/resque"
end

app/controllers/cpanel/users_controller.rb
# coding: UTF-8
class Cpanel::UsersController < CpanelController
  
  def index
    @users = User.desc("created_at").paginate(:page => params[:page], :per_page => 40)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end
  
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(cpanel_users_path, :notice => 'User 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end
  
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(cpanel_users_path, :notice => 'User 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.soft_delete

    respond_to do |format|
      format.html { redirect_to(cpanel_users_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:auth_callback]
  before_filter :init_user, :except => [:auth_callback, :login, :logout]

  def init_user
    @user = User.find_by_slug(params[:id])
    if @user.blank? or !@user.deleted.blank?
      render_404
    end
    @ask_to_user = Ask.new
  end

  def answered
    @per_page = 10
    @asks = Ask.normal.recent.find(@user.answered_ask_ids)
                  .paginate(:page => params[:page], :per_page => @per_page)
    set_seo_meta("#{@user.name}回答过的问题")
    if params[:format] == "js"
      render "/users/answered_asks.js"
    end
  end
  
  def asked_to
    @per_page = 10
    @asks = Ask.normal.recent.asked_to(@user.id)
                  .paginate(:page => params[:page], :per_page => @per_page)
    set_seo_meta("问#{@user.name}的问题")
    if params[:format] == "js"
      render "/asks/index.js"
    else
      render "asked"
    end
  end

  def show
    @per_page = 10
    @logs = Log.desc("$natural").where(:user_id => @user.id).paginate(:page => params[:page], :per_page => @per_page)
    set_seo_meta(@user.name)
    
    if params[:format] == "js"
      render "/logs/index.js"
    end
  end

  def asked
    @per_page = 10
    @asks = @user.asks.normal.recent
                  .paginate(:page => params[:page], :per_page => @per_page)
    set_seo_meta("#{@user.name}问过的问题")
    if params[:format] == "js"
      render "/asks/index.js"
    end
  end
  
  def following_topics
    @per_page = 20
    @topics = @user.followed_topics.desc("$natural")
                  .paginate(:page => params[:page], :per_page => @per_page)
    
    set_seo_meta("#{@user.name}关注的话题")
    if params[:format] == "js"
      render "following_topics.js"
    end
  end
  
  def followers
    @per_page = 20
    @followers = @user.followers.desc("$natural")
                  .paginate(:page => params[:page], :per_page => @per_page)
    
    set_seo_meta("关注#{@user.name}的人")
    if params[:format] == "js"
      render "followers.js"
    end
  end
  
  def following
    @per_page = 20
    @followers = @user.following.desc("$natural")
                  .paginate(:page => params[:page], :per_page => @per_page)
    
    set_seo_meta("#{@user.name}关注的人")
    if params[:format] == "js"
      render "followers.js"
    else
      render "followers"
    end
  end
  
  def follow
    if not @user
      render :text => "0"
      return
    end
    current_user.follow(@user)
    render :text => "1"
  end
  
  def unfollow
    if not @user
      render :text => "0"
      return
    end
    current_user.unfollow(@user)
    render :text => "1"
  end
  
  def login
    if !cookies[:TBSSO].blank?
      redirect_to "/auth/taobao/callback"
    else
      redirect_to "https://backyard.seraph.taobao.com/login/?url=http://#{Setting.domain}/auth/taobao/callback"
    end
  end
  
  def logout
    sign_out current_user
    redirect_to "https://backyard.seraph.taobao.com/login/?action=logout&url=#{root_url}"
  end

  def auth_callback
    if params[:provider] == "taobao"
      auto_taobao_sso
      return
    end
    
		auth = request.env["omniauth.auth"]  
		redirect_to root_path if auth.blank?
    provider_name = auth['provider'].gsub(/^t/,"").titleize
    Rails.logger.debug { auth }

		if current_user
      Authorization.create_from_hash(auth, current_user)
      flash[:notice] = "成功绑定了 #{provider_name} 帐号。"
			redirect_to edit_user_registration_path
		elsif @user = Authorization.find_from_hash(auth)
      sign_in @user
			flash[:notice] = "登陆成功。"
			redirect_to "/"
		else
      if Setting.allow_register
        @new_user = Authorization.create_from_hash(auth, current_user) #Create a new user
        if @new_user.errors.blank?
          sign_in @new_user
          flash[:notice] = "欢迎来自 #{provider_name} 的用户，你的帐号已经创建成功。"
          redirect_to "/"
        else
          flash[:notice] = "#{provider_name}的帐号提供信息不全，无法直接登陆，请先注册。"
          redirect_to "/register"
        end
      else
        flash[:alert] = "你还没有注册用户。"
        redirect_back_or_default "/login"
      end
		end
  end
  
  def auto_taobao_sso
    hash = {}
    cookies[:TBSSO].split("&").map { |row| hash[row.split("=")[0]] = row.split("=")[1] }
    auth  = { "uid" => hash["sign"], 
               "provider" => "taobao_sso",
               "user_info" => {
                 "name" => CGI::unescape(hash["cname"]).split("(").first,
                 "email" => hash["email"],
                 'slug' => hash['userid']
               }
             }
    if @user = Authorization.find_from_hash(auth)
      sign_in @user
			flash[:notice] = "登陆成功。"
			redirect_to "/"
    else
      @new_user = Authorization.create_from_hash(auth, current_user) #Create a new user
      if @new_user.errors.blank?
        sign_in @new_user
        flash[:notice] = "欢迎来自淘宝的用户，你的帐号已经创建成功。"
        redirect_to "/"
      else
        render :text => @new_user.errors
        flash[:notice] = "淘宝的帐号提供信息不全，无法直接登陆，请先注册。"

      end
    end
  end

end

app/helpers/cpanel/users_helper.rb
module Cpanel::UsersHelper
end

app/helpers/users_helper.rb
# coding: utf-8
module UsersHelper
  def user_name_tag(user, options = {})
    options[:url] ||= false
    return "" if user.blank?
    return "匿名用户" if !user.deleted.blank?
    return user.name if user.slug.blank?
    url = options[:url] == true ? user_url(user.slug) : user_path(user.slug)
    raw "<a#{options[:is_notify] == true ? " onclick=\"mark_notifies_as_read(this, '#{options[:notify].id}');\"" : ""} href=\"#{url}\" class=\"user\" title=\"#{h(user.name)}\">#{h(user.name)}</a>"
  end
  
  def user_avatar_tag(user,size)
    return "" if user.blank?
    return "" if user.slug.blank?
    if user.deleted.blank?
      url = eval("user.avatar.#{size}.url")
      if url.blank?
        url = ""
      end
      raw "<a href=\"#{user_path(user.slug)}\" class=\"user\" title=\"#{h(user.name)}\">#{image_tag(url, :class => size)}</a>"
    else
      raw image_tag("avatar/#{size.to_s}.jpg", :title => "匿名用户")
    end
  end

  def user_tagline_tag(user,options = {})
    return "" if user.blank?
    prefix = options[:prefix] || ""
    return "" if user.tagline.blank?
    raw "#{prefix}#{h(truncate(user.tagline, :length => 30))}"
  end

  def user_sex_title(user)
    return "" if user.blank?
    user.girl.blank? == true ? "他" : "她"
  end

  # 支持者列表
  def up_voter_links(up_voters, options = {})
    limit = options[:limit] || 3
    links = []
    hide_links = []
    up_voters.each_with_index do |u,i|
      link = user_name_tag(u)
      if i <= limit
        links << link
      else
        hide_links << link
      end
    end
    html = "<span class=\"voters\">#{links.join(",")}"
    if !hide_links.blank?
      html += "<a href=\"#\" onclick=\"$(this).next().show();$(this).replaceWith(',');return false;\" class=\"more\">(更多)</a><span class=\"hidden\">#{hide_links.join(",")}</span>"
    end
    html += "</span>"
    raw html
  end
end

app/views/users/1__head.html.erb.bak.erb
<%= content_for :scripts do %>
  <script type="text/javascript">
    var current_page = 2;
    function loadAsks(){
      App.loading();
      $.get("<%= request.path %>.js?page="+current_page,function(){
          App.loading(false);
      });
      return false;
    }
  </script>
<% end %>
<div class="uname">
	<div class="avatar"><%= image_tag(user.avatar.normal.url) %></div>
	<div class="detail">
		<h1 id="user_name"><%= user.name %><span>，</span><span id="user_tagline"><%= user.tagline %></span>
    <% if owner?user %>
      <%= in_place_edit_tag(user,:tagline,:rich => false, :text_id => "user_tagline") %> 
    <% end %></h1>
		<% if !user.website.blank? %>
		  <div class="website">
		    <a href="<%= user.website %>" rel="nofollow" target="_blank" id="user_website"><%= user.website %></a>
		    <% if owner?user %> <%= in_place_edit_tag(user,:website, :text_id => "user_website") %> <% end %>
		  </div>
		<% end %>
		<div class="bio">
			<span id="user_bio">
	      <% if @user.bio.blank? and (not owner?@user) %>
	        <%= @user.name %>还没来得及写他的个人介绍.
	      <% else %>
	        <%= md_body @user.bio %>
	      <% end %>
	    </span>
	    <% if owner?@user %> <%= in_place_edit_tag(@user,:bio,:type => :textarea, :text_id => "user_bio", :label => "修改个人经历") %> <% end %>
		</div>
	</div>
</div>

<div class="tabs">
  <a<%= ' class=actived' if params[:action] == "show" %> href="<%= user_path(user.slug) %>">主页</a>
	<a<%= ' class=actived' if params[:action] == "asked_to" %> href="<%= asked_to_user_path(user.slug) %>">问<%= current_user == user ? "我" : (user.girl ? "她" : "他") %>(<%= Ask.normal.asked_to(user.id).count %>)</a>
  <a<%= ' class=actived' if params[:action] == "asked" %> href="<%= asked_user_path(user.slug) %>">问过(<%= user.asks_count %>)</a>
  <a<%= ' class=actived' if params[:action] == "answered" %> href="<%= answered_user_path(user.slug) %>">回答过(<%= user.answered_ask_ids.count %>)</a>
	<!-- <a<%= ' class=actived' if params[:action] == "following" %> href="<%= following_user_path(user.slug) %>">关注(<%= user.following_ids.count %>)</a>
		<a<%= ' class=actived' if params[:action] == "followers" %> href="<%= followers_user_path(user.slug) %>">被关注(<%= user.follower_ids.count %>)</a> -->
	<a<%= ' class=actived' if params[:action] == "following_topics" %> href="<%= following_topics_user_path(user.slug) %>">关注的话题(<%= user.followed_topic_ids.count %>)</a>
</div>

<% if not owner? user %>
<div id="ask_to_user" class="simple_form">
  <h3>对<%= user.name %>提问:</h3>
  <form action="/asks" method="post">
    <div class="row">
      <%= auth_token %>
      <input type="hidden" name="ask[to_user_id]" value="<%= user.id %>" />
      <textarea type="text" class="text" onfocus="$(this).parent().next().show();" name="ask[title]"></textarea>
    </div>
    <div style="display:none">
      <div><a href="#" onclick="$(this).parent().next().show(); $(this).hide(); return false;">添加问题描述</a></div>
      <div class="row" style="display:none">
        <label>问题描述(可选):</label>
        <textarea type="text" class="text" name="ask[body]"></textarea>
      </div>
      <div class="actions">
        <button type="submit">提交问题</button>
      </div>
    </div>
  </form>
</div>
<br>
<% end %>

app/views/users/1_answered.html.erb.bak.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<div class="asks">
  <% @asks.each do |item| %>
    <%= render "/users/answered_ask", :item => item %>
  <% end %>
</div>
<% if @asks.length == @per_page %>
  <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();">查看更多...</a></div>
<% end %>
<%= render "sidebar", :user => @user %>

app/views/users/1_answered_asks.js.erb.bak.erb
<% if !@asks.blank? %>
  <% @asks.each do |item| %>
    $(".pagination").before('<%= escape_javascript(render("/users/answered_ask",:item => item)) %>');
  <% end %>
  current_page = "<%= (params[:page] || "1").to_i + 1 %>";
  <% if @asks.count < @per_page %>
  $(".pagination").remove();
  <% end %>
<% else %>
  $(".pagination").remove();
<% end %>

app/views/users/1_asked.mobile.erb.bak.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<div class="asks">
  <% @asks.each do |item| %>
    <%= render "/asks/ask", :item => item %>
  <% end %>
</div>
<% if @asks.length == @per_page %>
  <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();">查看更多...</a></div>
<% end %>
<%= render "sidebar", :user => @user %>

app/views/users/1_followers.html.erb.bak.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<ul class="followed-item followers-listing">
  <% @followers.each do |item| %>
    <%= render "follower", :follower => item %>
  <% end %>
	<% if @followers.length == @per_page %>
	<li class="pagination last"><a class="page_more" href="#" onclick="return loadAsks();">查看更多...</a></li>
	<% end %>
</ul>
<%= render "sidebar", :user => @user %>

app/views/users/1_followers.mobile.erb.bak.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<ul class="followed-item followers-listing">
  <% @followers.each do |item| %>
    <%= render "follower", :follower => item %>
  <% end %>
	<% if @followers.length == @per_page %>
	<li class="pagination last"><a class="page_more" href="#" onclick="return loadAsks();">查看更多...</a></li>
	<% end %>
</ul>
<%= render "sidebar", :user => @user %>

app/views/users/_answered_ask.erb
<div class="ask" ask-id="<%= item.id %>">
  <div class="title"><a href="/asks/<%= item.id %>"><%= item.title %></a></div>
    <div class="info">
      <%= user_name_tag(item.user) %> 提出的问题
      • <%= item.answers_count %> 个答案 
			<% if current_user %>
				<% if current_user.ask_followed?(item) %>
      	• <a href="#" onclick="return Asks.simple_unfollow(this,'<%= item.id %>')"><%=t(:cancel_concern)%></a> 
				<% else %>
				• <a href="#" onclick="return Asks.simple_follow(this,'<%= item.id %>')">关注</a> 
				<% end %>
				<% if current_user.ask_muted?(item.id) %>
				• <a href="#" onclick="return Asks.unmute(this,'<%= item.id %>')"><%=t(:unmasked)%></a> 
				<% else %>
      	• <a href="#" onclick="return Asks.mute(this,'<%= item.id %>')"><%=t(:not_interested)%></a> 
				<% end %>
			<% end %>
    </div> 
  <%
	mine_answer = item.answers.where(:user_id => @user.id).first
	if mine_answer
	%>
    <div class="last_answer answer">
      <div class="attr">
        <span class="votes"><%= mine_answer.votes_count %></span>
      </div>
      <div class="data">
      	<div class="md_body"><%= md_body(mine_answer.chomp_body) %></div>
      </div>
    </div>
  <% else %>
    <div class="md_body">
      <%= md_body(item.body) %>
    </div>
  <% end %>
</div>

app/views/users/_follower.erb
<li>
	<div class="item">
		<div class="left">
			<a href="/users/<%= follower.slug %>" title="<%= follower.name %>">
				<%= user_avatar_tag(follower, :small) %>
			</a>
		</div>
		<div class="right">
			<p><a href="<%= user_path(follower.slug) %>"><%= follower.name %></a></p>
			<p class="tagline"><%= follower.tagline %></p>
		</div>
	</div>
	<% if current_user %>
	<div class="action">
		<% if current_user.followed?(follower) %>
		<a class="flat_button small" href="#" onclick="return Users.unfollow(this, '<%= follower.slug %>','small');"><%=t(:cancel_concern)%></a>
		<% else %>
		<a class="green_button small" href="#" onclick="return Users.follow(this, '<%= follower.slug %>','small');">关注</a>
		<% end %>
	</div>
	<% end %>
</li>

app/views/users/_sidebar.mobile.erb
<div id="user_sidebar" class="sidebar">

  <div class="box gray">
    <h2></h2>
    <ul class="follow-stats">
      <li>
        <a href="<%= followers_user_path(@user.slug) %>"><strong>
        <%= @user.follower_ids.size %></strong>
        <span>关注<%= user_sex_title(@user) %>的人</span>
        </a>
      </li>
      <li class="last">
        <a href="<%= following_user_path(@user.slug) %>"><strong>
        <%= @user.following_ids.size %></strong>
        <span><%= user_sex_title(@user) %><%=t(:persons_of_concern)%></span>
        </a>
      </li>
    </ul>
    <div class="user-regdate"><%=t(:registered_in)%> <%= l @user.created_at.to_date, :format => :long %></div>
  </div>

  <% if @user.followed_topic_ids.size > 0 %>
  <div class="box gray">
  <h2>关注 <a href="<%= following_topics_user_path(@user.slug) %>"><%= @user.followed_topic_ids.size %><%=t(:topics)%></a></h2>
  <ul class="followed-item">
    <% for topic in @user.followed_topics.desc("$natural").limit(7) %>
    <%= render "topic", :topic => topic %>
    <% end %>
  </ul>
  </div>
  <% end %>

</div>

app/views/users/asked.html.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<div class="asks">
  <% @asks.each do |item| %>
    <%= render "/asks/ask", :item => item %>
  <% end %>
</div>
<% if @asks.length == @per_page %>
  <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();"><%=t(:see_more)%>...</a></div>
<% end %>
<%= render "sidebar", :user => @user %>

app/views/users/asked.mobile.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<div class="asks">
  <% @asks.each do |item| %>
    <%= render "/asks/ask", :item => item %>
  <% end %>
</div>
<% if @asks.length == @per_page %>
  <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();"><%=t(:see_more)%>...</a></div>
<% end %>
<%= render "sidebar", :user => @user %>

app/views/users/followers.html.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<ul class="followed-item followers-listing">
  <% @followers.each do |item| %>
    <%= render "follower", :follower => item %>
  <% end %>
	<% if @followers.length == @per_page %>
	<li class="pagination last"><a class="page_more" href="#" onclick="return loadAsks();"><%=t(:see_more)%>...</a></li>
	<% end %>
</ul>
<%= render "sidebar", :user => @user %>

app/views/users/followers.mobile.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<ul class="followed-item followers-listing">
  <% @followers.each do |item| %>
    <%= render "follower", :follower => item %>
  <% end %>
	<% if @followers.length == @per_page %>
	<li class="pagination last"><a class="page_more" href="#" onclick="return loadAsks();"><%=t(:see_more)%>...</a></li>
	<% end %>
</ul>
<%= render "sidebar", :user => @user %>

app/views/users/following_topics.mobile.erb
<div class="user_profile">
  <%= render "head", :user => @user %>
</div>
<ul class="followed-item topic-listing">
  <% @topics.each do |item| %>
    <%= render "topic", :topic => item %>
  <% end %>
	<% if @topics.length == @per_page %>
	<li class="pagination last"><a class="page_more" href="#" onclick="return loadAsks();"><%=t(:see_more)%>...</a></li>
	<% end %>
</ul>
<%= render "sidebar", :user => @user %>