config/routes.rb
Quora::Application.routes.draw do
  root :to => "home#index"

  match "/uploads/*path" => "gridfs#serve"
  match "/update_in_place" => "home#update_in_place"
  match "/muted" => "home#muted"
  match "/newbie" => "home#newbie"
  match "/followed" => "home#followed"
  match "/recommended" => "home#recommended"
  match "/mark_notifies_as_read" => "home#mark_notifies_as_read"
  match "/mute_suggest_item" => "home#mute_suggest_item"
  match "/report" => "home#report"
  match "/about" => "home#about"
  match "/doing" => "logs#index"

  # devise_for :users, :path => '', :path_names => {:sign_in => "login", :sign_out => "logout", :sign_up => "register", :registration }
  devise_for :users,  :controllers => { :registrations => "registrations" } do
    # get "/register", :to => "registrations#new" 
    # get "/login", :to => "devise/sessions#new" 
    # get "/logout", :to => "devise/sessions#destroy" 
  end
  resources :users do
    member do
      get "answered"
      get "asked"
      get "asked_to"
      get "follow"
      get "unfollow"
      get "followers"
      get "following"
      get "following_topics"
      get "following_asks"
    end
  end
  match "login", :to => "users#login"
  match "logout", :to => "users#logout"
  match "auth/:provider/callback", :to => "users#auth_callback"  

  resources :search do
    collection do
      get "all"
      get "topics"
      get "asks"
      get "users"
    end
  end
  
  resources :asks do
    member do
      get "spam"
      get "follow"
      get "unfollow"
      get "mute"
      get "unmute"
      post "answer"
      post "update_topic"
      get "update_topic"
      get "redirect"
      get "invite_to_answer"
      get "share"
      post "share"
    end
  end

  resources :answers do
    member do
      get "vote"
      get "spam"
      get "thank"
    end
  end
  resources :comments 

  resources :topics, :constraints => { :id => /[a-zA-Z\w\s\.%\-_]+/ } do
    member do
      get "follow"
      get "unfollow"
    end
  end
  resources :logs
  resources :inbox

  namespace :cpanel do
    root :to =>  "home#index"
    resources :users
    resources :asks
    resources :answers
    resources :topics
    resources :comments
    resources :report_spams
    resources :notices
  end

  mount Resque::Server, :at => "/cpanel/resque"
end

app/controllers/cpanel/home_controller.rb
class Cpanel::HomeController < CpanelController
  def index
    redirect_to cpanel_asks_path
  end
end

app/controllers/home_controller.rb
# coding: utf-8
class HomeController < ApplicationController
  before_filter :require_user_text, :only => [:update_in_place,:mute_suggest_item]
  before_filter :require_user, :except => [:about,:index]

  def index
    @per_page = 20
    if current_user
      @notifies, @notifications = current_user.unread_notifies
      
      if current_user.following_ids.size == 0 and current_user.followed_ask_ids.size == 0 and current_user.followed_topic_ids.size == 0
        redirect_to newbie_path and return
      else
        # TODO: 这里需要过滤掉烂问题
        @logs = Log.any_of({:user_id.in => current_user.following_ids},
                           {:target_id.in => current_user.followed_ask_ids})
                          .and(:action.in => ["NEW", "AGREE", "EDIT"], :_type.in => ["AskLog", "AnswerLog", "CommentLog", "UserLog"])
                          .excludes(:user_id => current_user.id).desc("$natural")
                          .paginate(:page => params[:page], :per_page => @per_page)
        
        if @logs.count < 1
          @asks = Ask.normal.any_of({:topics.in => current_user.followed_topics.map{|t| t.name}}).not_in(:follower_ids => [current_user.id])
          @asks = @asks.includes(:user,:last_answer,:last_answer_user,:topics)
                        .exclude_ids(current_user.muted_ask_ids)
                        .desc(:answers_count,:answered_at)
                        .paginate(:page => params[:page], :per_page => @per_page)
                        
          if params[:format] == "js"
            render "/asks/index.js"
          end
        else
          if params[:format] == "js"
            render "/logs/index.js"
          else
            render "/logs/index"
          end
        end
      end
    else
      @asks = Ask.normal.recent.paginate(:page => params[:page], :per_page => @per_page)
      if params[:format] == "js"
        render "/asks/index.js"
      end
    end
  end
  
  def newbie
    @notifies, @notifications = current_user.unread_notifies
    ask_logs = Log.any_of({:_type => "AskLog"}, {:_type => "UserLog", :action.in => ["FOLLOW_ASK", "UNFOLLOW_ASK"]}).where(:created_at.gte => (Time.now - 12.hours))
    answer_logs = Log.any_of({:_type => "AnswerLog"}, {:_type => "UserLog", :action => "AGREE"}).where(:created_at.gte => (Time.now - 12.hours))
    @asks = Ask.normal.any_of({:_id.in => ask_logs.map {|l| l.target_id}.uniq}, {:_id.in => answer_logs.map {|l| l.target_parent_id}.uniq}).order_by(:answers_count.asc, :views_count.asc)
    h = {} 
    # 将回答次数*topic，以加入回答次数
    @hot_topics = @asks.inject([]) { |memo, ask|
      memo += ask.topics
    }
    @hot_topics.delete("者也")
    @hot_topics.delete("知乎")
    @hot_topics.delete("反馈")
    @hot_topics.delete("zheye")
    @hot_topics.delete("Quora")
    @hot_topics.delete("quora")
    
    @hot_topics.each { |str| 
      h[str] = (h[str] || 0) + 1 
    }
    @hot_topics = h.sort{|a, b|b[1]<=>a[1]}.collect{|tmp|tmp[0]}[0..8]
  end
  
  def timeline
    @per_page = 20
    # @logs = Log.any_in(:user_id => curr)
  end
  
  def followed
    @per_page = 20
    @asks = current_user ? current_user.followed_asks.normal : Ask.normal
    @asks = @asks.includes(:user,:last_answer,:last_answer_user,:topics)
                  .exclude_ids(current_user.muted_ask_ids)
                  .desc(:answered_at,:id)
                  .paginate(:page => params[:page], :per_page => @per_page)

    if params[:format] == "js"
      render "/asks/index.js"
    else
      render "index"
    end
  end
  
  def recommended
    @per_page = 20
    @asks = current_user ? Ask.normal.any_of({:topics.in => current_user.followed_topics.map{|t| t.name}}).not_in(:follower_ids => [current_user.id]).and(:answers_count.lt => 1) : Ask.normal
    @asks = @asks.includes(:user,:last_answer,:last_answer_user,:topics)
                  .exclude_ids(current_user.muted_ask_ids)
                  .desc(:answers_count,:answered_at)
                  .paginate(:page => params[:page], :per_page => @per_page)

    if params[:format] == "js"
      render "/asks/recommended.js"
    end
  end

  # 查看用户不感兴趣的问题
  def muted
    @per_page = 20
    @asks = Ask.normal.includes(:user,:last_answer,:last_answer_user,:topics)
                  .only_ids(current_user.muted_ask_ids)
                  .desc(:answered_at,:id)
                  .paginate(:page => params[:page], :per_page => @per_page)

    set_seo_meta("我屏蔽掉的问题")

    if params[:format] == "js"
      render "/asks/index.js"
    else
      render "index"
    end
  end

  def update_in_place
    # TODO: Here need to chack permission
    klass, field, id = params[:id].split('__')
    puts params[:id]

    # 验证权限,用户是否有修改制定信息的权限
    case klass
    when "user" then return if current_user.id.to_s != id
    end
    
    params[:value] = simple_format(params[:value].to_s.strip) if params[:did_editor_content_formatted] == "no"

    object = klass.camelize.constantize.find(id)
    update_hash = {field => params[:value]}
    if ["ask","topic"].include?(klass) and current_user
      update_hash[:current_user_id] = current_user.id
    end
    if object.update_attributes(update_hash)
      render :text => object.send(field).to_s
    else
      Rails.logger.info "object.errors.full_messages: #{object.errors.full_messages}"
      render :text => object.errors.full_messages.join("\n"), :status => 422
    end
  end

  def about
    set_seo_meta("关于")
    @users = User.any_in(:email => Setting.admin_emails)
  end
  
  def mark_notifies_as_read
    if !params[:ids]
      render :text => "0"
    else
      notifications = current_user.notifications.any_in(:_id => params[:ids].split(","))
      notifications.each do |notify|
        # Rails.logger.info "mark_notifies_as_read\n"
        notify.update_attribute(:has_read, true)
      end
      render :text => "1"
    end
  end

  def report
    name = "访客"
    if current_user
      name = current_user.name
    end
    ReportSpam.add(params[:url],params[:desc],name)
    flash[:notice] = "举报信息已经提交，谢谢你。"
    redirect_to params[:url]
  end

  def mute_suggest_item
    UserSuggestItem.mute(current_user.id, params[:type].strip.titleize, params[:id])
    render :text => "1"
  end

end

app/views/home/1__recommended_topic.html.erb.bak.erb
<li>
  <div class="mute">
    <a href="#" rel="tipsyt" title="不感兴趣" onclick="return Users.mute_suggest_item(this,'Topic','<%= topic.id %>');"></a>
  </div>
  <div class="info clearfix">
    <div class="item">
      <div class="left">
        <%= topic_cover_tag(topic,:small) %>
      </div>
      <div class="right">
        <%= topic_name_tag(topic, :prefix => "#") %>
        <div class="tagline">话题</div>
      </div>
    </div>
    <div class="action">
      <a class="green_button small" href="#" onclick="return Topics.follow(this, '<%= topic.name %>','small');">关注</a>
    </div>
  </div>
</li>

app/views/home/1__recommended_user.html.erb.bak.erb
<li>
  <div class="mute">
    <a href="#" rel="tipsyt" title="不感兴趣" onclick="return Users.mute_suggest_item(this,'User','<%= follower.id %>');"></a>
  </div>
  <div class="info clearfix">
    <div class="item">
      <div class="left">
        <%= user_avatar_tag(follower,:small) %>
      </div>
      <div class="right">
        <p><%= user_name_tag(follower) %></p>
        <p class="tagline"><%= truncate(follower.tagline,:length => 9, :truncate_string =>"…") %></p>
      </div>
    </div>
    <div class="action">
      <a class="green_button small" href="#" onclick="return Users.follow(this, '<%= follower.slug %>','small');">关注</a>
    </div>
  </div>
</li>

app/views/home/1_about.html.erb.bak.erb
<%= content_for :styles do %>
  <style type="text/css">
    #about {}
    #about h2 { border-top:1px dashed #ccc; padding-top:10px; margin-top:20px; margin-bottom:10px; font-size:14px; }
  </style>
<% end %>
<div id="about">
  <h1>关于者也</h1>
  <div class="md_body">
    我们是一群向往自由开放的程序员，立志构建一个开放的问答社区站点。<br />
    我们乐于分享我们的项目源代码以及设计思路，以供有非盈利性目的的个人，公司使用。
  </div>
  <h2>团队成员</h2>
  <div class="team">
    <% @users.each do |u| %>
      <%= user_avatar_tag(u,:normal) %>
    <% end %>
  </div>
  <h2>贡献者</h2>
  <div class="contributors">
    <ul>
      <li><a href="https://github.com/saberma">Saberma</a></li>
			<li><a href="https://github.com/caili">caili</a></li>
			<li><a href="https://github.com/hooopo">Hooopo</a></li>
    </ul>
  </div>
</div>
<%= content_for :sidebar do %>
  <div class="box">
    <h2>常见问题</h2>
    <ul> 
      <li><a href="http://zheye.org/asks/4d92a076fd503c480e00002a">为啥起“者也”这个名字？</a></li> 
      <li><a href="http://zheye.org/asks/4d95f33bfd503c3bf2000011">者也每天都做了哪些更新？</a></li> 
      <li><a href="http://zheye.org/asks/4d95a178fd503c6ad6000030">代码部署和二次开发容易吗？</a></li> 
      <li><a href="http://zheye.org/asks/4d95ee5bfd503c2652000039">者也比知乎好在哪里？</a></li> 
      <li><a href="http://zheye.org/asks/4d92db71fd503c7c03000188">用户名称可以修改么？</a></li> 
      <li><a href="http://zheye.org/asks/4d94325efd503c17a5000004">者也是个怎样的问答社区？</a></li> 
    </ul>
  </div>
<% end %>

app/views/home/1_index.html.erb.bak.erb
<%= render 'asks/base' %>
<%= content_for :scripts do %>
  <script type="text/javascript">
    var current_page = 2;
    function loadAsks(){
      App.loading();
      $.get("<%= request.path %>.js?page="+current_page,function(){
          App.loading(false);
      });
      return false;
    }
  </script>
<% end %>

<div id="asks">
  <% @asks.each do |item| %>
    <%= render "asks/ask", :item => item %>
  <% end %>
  <% if @asks.length == @per_page %>
    <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();">查看更多...</a></div>
  <% end %>
</div>
<%= render "asks/sidebar" %>

app/views/home/1_index.mobile.erb.bak.erb
<%= render 'asks/base' %>
<%= content_for :scripts do %>
  <script type="text/javascript">
    var current_page = 2;
    function loadAsks(){
      App.loading();
      $.get("<%= request.path %>.js?page="+current_page,function(){
          App.loading(false);
      });
      return false;
    }
  </script>
<% end %>

<div id="asks">
  <% @asks.each do |item| %>
    <%= render "asks/ask", :item => item %>
  <% end %>
  <% if @asks.length == @per_page %>
    <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();">查看更多...</a></div>
  <% end %>
</div>
<%= render "asks/sidebar" %>

app/views/home/1_newbie.html.erb.bak.erb
<%= render :partial => 'logs/notifies' %>

<div class="newbie">
	<h1>欢迎来到者也</h1>
	<div class="welcome">
		这里是一个满足你各种好奇、求知、探索、社交、讨论欲望的地方。她由来自无数行业无数地方的 <span class="orange">人们</span>、各种他们提出的 <span class="green">问题</span> 以及各个用以组织问题的 <span class="purple">话题</span> 组成。你可以利用顶部的搜索框来尝试搜索你感兴趣的关键词，并关注一些话题、问题或者人。当你关注过之后，你可以看到这些人、问题的动态，还可以在“<a href="/followed">我关注的问题</a>”里看到你感兴趣的新老问题。
	</div>
	<br>
	有时候去“<a href="<%= doing_path %>">者也正在发生</a>”闲逛也是不错的发现感兴趣的问题和讨论的方法。
	<br>
	<br>
	
	<% if !@hot_topics.nil? and @hot_topics.size > 0 %>
	<h2>或者你可以去看看这些最近比较热门的话题：</h2>
	<ul class="hot-topics">
		<% for topic in @hot_topics %>
		<li><a href="<%= topic_path(topic) %>"><%= topic %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<% 
	waiting_asks = @asks.where(:answers_count.lte => 2).where(:created_at.lte => (Time.now - 12.hours)).limit(10)
	if waiting_asks.size > 0
	%>
	<br>
	<h2>又或者是去给这些等待回答的问题添加一些你所知道的答案：</h2>
	<ul class="hot-asks">
		<% for ask in waiting_asks %>
		<li><a href="<%= ask_path(ask) %>"><%= ask.title %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<% if @asks.size > 0 %>
	<br>
	<h2>还可以看看这些热门问题：</h2>
	<ul class="hot-asks">
		<% for ask in @asks.order_by(:answers_count.desc, :views_count.desc).limit(10) %>
		<li><a href="<%= ask_path(ask) %>"><%= ask.title %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<br>
	<p>
		祝你在“者也”愉快。
	</p>
</div>
<%= render "asks/sidebar" %>

app/views/home/1_newbie.mobile.erb.bak.erb
<%= render :partial => 'logs/notifies' %>

<div class="newbie">
	<h1>欢迎来到者也</h1>
	<div class="welcome">
		这里是一个满足你各种好奇、求知、探索、社交、讨论欲望的地方。她由来自无数行业无数地方的 <span class="orange">人们</span>、各种他们提出的 <span class="green">问题</span> 以及各个用以组织问题的 <span class="purple">话题</span> 组成。你可以利用顶部的搜索框来尝试搜索你感兴趣的关键词，并关注一些话题、问题或者人。当你关注过之后，你可以看到这些人、问题的动态，还可以在“<a href="/followed">我关注的问题</a>”里看到你感兴趣的新老问题。
	</div>
	<br>
	有时候去“<a href="<%= doing_path %>">者也正在发生</a>”闲逛也是不错的发现感兴趣的问题和讨论的方法。
	<br>
	<br>
	
	<% if !@hot_topics.nil? and @hot_topics.size > 0 %>
	<h2>或者你可以去看看这些最近比较热门的话题：</h2>
	<ul class="hot-topics">
		<% for topic in @hot_topics %>
		<li><a href="<%= topic_path(topic) %>"><%= topic %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<% 
	waiting_asks = @asks.where(:answers_count.lte => 2).where(:created_at.lte => (Time.now - 12.hours)).limit(10)
	if waiting_asks.size > 0
	%>
	<br>
	<h2>又或者是去给这些等待回答的问题添加一些你所知道的答案：</h2>
	<ul class="hot-asks">
		<% for ask in waiting_asks %>
		<li><a href="<%= ask_path(ask) %>"><%= ask.title %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<% if @asks.size > 0 %>
	<br>
	<h2>还可以看看这些热门问题：</h2>
	<ul class="hot-asks">
		<% for ask in @asks.order_by(:answers_count.desc, :views_count.desc).limit(10) %>
		<li><a href="<%= ask_path(ask) %>"><%= ask.title %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<br>
	<p>
		祝你在“者也”愉快。
	</p>
</div>
<%= render "asks/sidebar" %>

app/views/home/1_recommended.html.erb.bak.erb
<%= render 'asks/base' %>
<%= content_for :scripts do %>
  <script type="text/javascript">
    var current_page = 2;
    function loadAsks(){
      App.loading();
      $.get("<%= request.path %>.js?page="+current_page,function(){
          App.loading(false);
      });
      return false;
    }
  </script>
<% end %>

<div class="listing-title">你或许能回答：</div>

<div id="asks">
  <% @asks.each do |item| %>
    <%= render "asks/recommended_ask", :item => item %>
  <% end %>
  <% if @asks.length == @per_page %>
    <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();">查看更多...</a></div>
  <% end %>
</div>
<%= render "asks/sidebar" %>

app/views/home/_recommended_user.html.erb
<li>
  <div class="mute">
    <a href="#" rel="tipsyt" title="不感兴趣" onclick="return Users.mute_suggest_item(this,'User','<%= follower.id %>');"></a>
  </div>
  <div class="info clearfix">
    <div class="item">
      <div class="left">
        <%= user_avatar_tag(follower,:small) %>
      </div>
      <div class="right">
        <p><%= user_name_tag(follower) %></p>
        <p class="tagline"><%= truncate(follower.tagline,:length => 9, :truncate_string =>"…") %></p>
      </div>
    </div>
    <div class="action">
      <a class="green_button small" href="#" onclick="return Users.follow(this, '<%= follower.slug %>','small');">关注</a>
    </div>
  </div>
</li>

app/views/home/about.html.erb
<%= content_for :styles do %>
  <style type="text/css">
    #about {}
    #about h2 { border-top:1px dashed #ccc; padding-top:10px; margin-top:20px; margin-bottom:10px; font-size:14px; }
  </style>
<% end %>
<div id="about">
  <h1><%=t(:who_is_also_on_the)%></h1>
  <div class="md_body">
    <%=t(:we_are_a_group_of_programmers_who_aspire_to_a_free_and_open)%>，<%=t(:determined_to_build_an_open_question_and_answer_community_site)%>。<br />
    <%=t(:we_are_happy_to_share_our_project_source_code_and_design_ideas)%>，<%=t(:for_a_nonprofit_personal_purposes)%>，<%=t(:companies_use)%>。
  </div>
  <h2><%=t(:team_members)%></h2>
  <div class="team">
    <% @users.each do |u| %>
      <%= user_avatar_tag(u,:normal) %>
    <% end %>
  </div>
  <h2><%=t(:contributors)%></h2>
  <div class="contributors">
    <ul>
      <li><a href="https://github.com/saberma">Saberma</a></li>
			<li><a href="https://github.com/caili">caili</a></li>
			<li><a href="https://github.com/hooopo">Hooopo</a></li>
    </ul>
  </div>
</div>
<%= content_for :sidebar do %>
  <div class="box">
    <h2><%=t(:frequently_asked_questions)%></h2>
    <ul> 
      <li><a href="http://zheye.org/asks/4d92a076fd503c480e00002a"><%=t(:why_play)%>“<%=t(:are_also)%>”<%=t(:the_name)%>？</a></li> 
      <li><a href="http://zheye.org/asks/4d95f33bfd503c3bf2000011"><%=t(:are_also)%>每天都做了哪些更新？</a></li> 
      <li><a href="http://zheye.org/asks/4d95a178fd503c6ad6000030"><%=t(:code_deploy_and_easy_for_secondary_development)%>？</a></li> 
      <li><a href="http://zheye.org/asks/4d95ee5bfd503c2652000039"><%=t(:are_also)%>比知乎好在哪里？</a></li> 
      <li><a href="http://zheye.org/asks/4d92db71fd503c7c03000188"><%=t(:what_can_change_the_user_name)%>？</a></li> 
      <li><a href="http://zheye.org/asks/4d94325efd503c17a5000004"><%=t(:are_also)%>是个怎样的问答社区？</a></li> 
    </ul>
  </div>
<% end %>

app/views/home/index.html.erb
<%= render 'asks/base' %>
<%= content_for :scripts do %>
  <script type="text/javascript">
    var current_page = 2;
    function loadAsks(){
      App.loading();
      $.get("<%= request.path %>.js?page="+current_page,function(){
          App.loading(false);
      });
      return false;
    }
  </script>
<% end %>

<div id="asks">
  <% @asks.each do |item| %>
    <%= render "asks/ask", :item => item %>
  <% end %>
  <% if @asks.length == @per_page %>
    <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();"><%=t(:see_more)%>...</a></div>
  <% end %>
</div>
<%= render "asks/sidebar" %>

app/views/home/index.mobile.erb
<%= render 'asks/base' %>
<%= content_for :scripts do %>
  <script type="text/javascript">
    var current_page = 2;
    function loadAsks(){
      App.loading();
      $.get("<%= request.path %>.js?page="+current_page,function(){
          App.loading(false);
      });
      return false;
    }
  </script>
<% end %>

<div id="asks">
  <% @asks.each do |item| %>
    <%= render "asks/ask", :item => item %>
  <% end %>
  <% if @asks.length == @per_page %>
    <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();"><%=t(:see_more)%>...</a></div>
  <% end %>
</div>
<%= render "asks/sidebar" %>

app/views/home/newbie.html.erb
<%= render :partial => 'logs/notifies' %>

<div class="newbie">
	<h1><%=t(:welcome_to_those_who_have)%></h1>
	<div class="welcome">
		<%=t(:here_is_a_variety_to_satisfy_your_curiosity)%>、<%=t(:knowledge)%>、<%=t(:discover)%>、<%=t(:social)%>、<%=t(:desire_to_place_the_discussion)%>。<%=t(:her_numerous_industries_from_many_parts_of_the)%> <span class="orange"><%=t(:people)%></span>、<%=t(:they_proposed_a_variety_of)%> <span class="green"><%=t(:problem)%></span> 以及各个用以组织<%=t(:problem)%>的 <span class="purple"><%=t(:topic)%></span> <%=t(:composition)%>。<%=t(:you_can_use_the_search_box_at_the_top_to_try_to_search_for_the_keywords_you_are_interested_in)%>，并关注一些<%=t(:topic)%>、<%=t(:problem)%>或者人。<%=t(:when_you_look_over_after)%>，<%=t(:you_can_see_these_people)%>、<%=t(:problem)%>的动态，<%=t(:you_can_also)%>“<a href="/followed">我关注的<%=t(:problem)%></a>”里看到你感兴趣的新老<%=t(:problem)%>。
	</div>
	<br>
	<%=t(:sometimes_go)%>“<a href="<%= doing_path %>"><%=t(:were_also_taking_place)%></a>”闲逛也是不错的发现感兴趣的<%=t(:problem)%>和讨论的方法。
	<br>
	<br>
	
	<% if !@hot_topics.nil? and @hot_topics.size > 0 %>
	<h2>或者你可以去看看这些最近比较热门的<%=t(:topic)%>：</h2>
	<ul class="hot-topics">
		<% for topic in @hot_topics %>
		<li><a href="<%= topic_path(topic) %>"><%= topic %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<% 
	waiting_asks = @asks.where(:answers_count.lte => 2).where(:created_at.lte => (Time.now - 12.hours)).limit(10)
	if waiting_asks.size > 0
	%>
	<br>
	<h2>又或者是去给这些等待回答的<%=t(:problem)%>添加一些你所知道的答案：</h2>
	<ul class="hot-asks">
		<% for ask in waiting_asks %>
		<li><a href="<%= ask_path(ask) %>"><%= ask.title %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<% if @asks.size > 0 %>
	<br>
	<h2>还可以看看这些热门<%=t(:problem)%>：</h2>
	<ul class="hot-asks">
		<% for ask in @asks.order_by(:answers_count.desc, :views_count.desc).limit(10) %>
		<li><a href="<%= ask_path(ask) %>"><%= ask.title %></a></li>
		<% end %>
	</ul>
	<% end %>
	
	<br>
	<p>
		<%=t(:good_luck_in_your)%>“<%=t(:are_also)%>”<%=t(:happy)%>。
	</p>
</div>
<%= render "asks/sidebar" %>

app/views/home/recommended.html.erb
<%= render 'asks/base' %>
<%= content_for :scripts do %>
  <script type="text/javascript">
    var current_page = 2;
    function loadAsks(){
      App.loading();
      $.get("<%= request.path %>.js?page="+current_page,function(){
          App.loading(false);
      });
      return false;
    }
  </script>
<% end %>

<div class="listing-title"><%=t(:you_may_be_able_to_answer)%>：</div>

<div id="asks">
  <% @asks.each do |item| %>
    <%= render "asks/recommended_ask", :item => item %>
  <% end %>
  <% if @asks.length == @per_page %>
    <div class="pagination"><a class="page_more" href="#" onclick="return loadAsks();"><%=t(:see_more)%>...</a></div>
  <% end %>
</div>
<%= render "asks/sidebar" %>